version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: shell_script/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: shell_script/start_container.sh
      timeout: 300
      runas: root
