version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_URL: /myapp/docker_url
    DOCKER_REGISTRY_USERNAME: /myapp/docker_username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker_password

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r simple_python_app/requirements.txt
  build:
    commands:
      - echo "Running Tests"
      - cd "simple_python_app"
      - echo "Logging to Docker Hub"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - echo "Building the Docker image"
      - docker build -t "${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_USERNAME}/simple-python-app:latest" .
      - echo "Pushing Docker Image to Docker Registry"
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
  post_build:
    commands:
      - echo "Build is completed successfully"
      